# Generated by Django 4.2.4 on 2023-09-06 18:13

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pracTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('deposit', models.BigIntegerField(validators=[polls.models.validate_positive])),
                ('score', models.IntegerField()),
            ],
        ),
    ]
